### ISSUE TITLE
Option to skip episode .nfo files

### ISSUE THREAD

**Issue by jmonsted** [MarkSummerville/tvrename#133]
Hiya,

I'm a happy user with a large collection managed by TVrename and fed to Plex. Plex likes to have a show .nfo to ensure a good match for its scraper, but i don't want the individual episode .nfo files. I would very much like to see a couple extra checkboxes in settings for "XBMC NFO files for: [X] Shows, [ ] Episodes" instead of the current one that does both.

**Comment by MarkSummerville** [comment]
Hi,

Shouldn't be too difficult to do. It may have to wait for a little while as we are trudging through a TVDB update at the moment. Once we are done with this I can add this in.

Cheers - thanks for the suggestion

Mark

**Comment by jmonsted** [comment]
It seems to be doing exactly what i wanted. Thank you!
