### ISSUE TITLE
Padding Seasons to two digits should not pad to three digits

### ISSUE THREAD

**Issue by lkeels** [MarkSummerville/tvrename#134]
Currently, if the box is checked to pad seasons to two digits, shows with seasons 10 and up end up with three digits, which causes torrent searches to fail. Padding should only occur on single digit seasons.

**Comment by MarkSummerville** [comment]
Hi,

Do you have a screenshot showing this please? I have tried and it works correctly. Which version are you using?

**Comment by lkeels** [comment]
That was five months ago. I gave up and moved on to Sonarr.
